### ISSUE TITLE
开关中使用options设置多套字符集过滤，请问在key_binder里面应该怎么配置快捷键？ 

### ISSUE THREAD

**Issue by imtinge** [LEOYoon-Tsaw/Rime_collections#14]
开关中使用options设置多套字符集过滤，请问在key_binder里面应该怎么快捷键？ 
```
……
switches:
  - name: ascii_mode
    reset: 0
    states: [ 中文, 西文 ]
  - name: full_shape
    states: [ 半角, 全角 ]
  - options: [ gb2312, gbk, utf-8 ]
    states:
      - 字集 → GB2312
      - 字集 → GBK
      - 字集 → UTF-8
    reset: 0
……
  filters:
    - charset_filter@gb2312
    - charset_filter@gbk
    - charset_filter@utf-8
……
key_binder:
  import_preset: default
  bindings:
    - {accept: semicolon, send: 2, when: has_menu}
    - {accept: apostrophe, send: 3, when: has_menu}
    - {accept: Control+Shift+g, toggle: gbk, when: always}
```
这样写在schema文件中无效，请问应该如何设置，谢谢
