### ISSUE TITLE
Reverse Lookup Filter 的行为与其他 Filter 不同

### ISSUE THREAD

**Issue by lanluoxiao** [LEOYoon-Tsaw/Rime_collections#7]
由于 Rime 不再内置袖珍简化字拼音，我想尝试能否用明月拼音实现简体形码的反查。以 `wubi86` 为例，我的思路如下：

## 一、设定拼音副翻译器

添加如下条目

```yaml
engine/segmentors/affix_segmentor@pinyin
engine/translators/script_translator@pinyin
recognizer/patterns/pinyin: "`[a-z]*;?$"
```

```yaml
pinyin:
  tag: pinyin
  prefix: "`"
  dictionary: luna_pinyin
  tips: 【拼音】
```

## 二、设定拼音反查滤镜

```yaml
engine/filters:
  - simplifier
  - reverse_lookup_filter@pinyin_lookup
```

```yaml
pinyin_lookup:
  tags: [ pinyin ]
  dictionary: wubi86
  overwrite_comment: true
```

---

按照我的设想，当输入反查码时，反查码会打上 `pinyin` 标签从而由 `pinyin` 副翻译器翻译，翻译得到的结果首先通过 `simplifier` 滤镜得到简体字，然后通过 `pinyin_lookup` 滤镜得到五笔编码。但是实际上按这种方式得到的五笔编码仍然是繁体的，如「体」字的反查结果是繁体编码（memu）而不是简体编码（wsgg），如下：

![image](https://user-images.githubusercontent.com/45678887/89728839-caa9d780-da62-11ea-80c5-fca171b072eb.png)

那么，结果表明 `pinyin_lookup` 并没有在 `simplifier` 之后响应，而是在其之前响应，这是否意味着 `reverse_lookup_filter` 与其他滤镜的行为不同，它不是按 `filters` 中指定的顺序进行响应，而是在翻译完成后立刻响应？

如果是的话，还有没有其他方式可以实现这个需求？

**Comment by lanluoxiao** [comment]
这里是全部的 `wubi86.schema.yaml` 配置： @LEOYoon-Tsaw 

```yaml
# Rime schema
# encoding: utf-8

schema:
  name: 五笔
  schema_id: wubi86
  version: "0.2"
  dependencies:
    - luna_pinyin

switches:
  - name: ascii_mode
    reset: 0
  - name: full_shape
    states: [ 半角, 全角 ]
    reset: 0

engine:
  processors:
    - ascii_composer
    - recognizer
    - key_binder
    - speller
    - punctuator
    - selector
    - navigator
    - express_editor
  segmentors:
    - ascii_segmentor
    - matcher
    - abc_segmentor
    - affix_segmentor@pinyin
    - punct_segmentor
    - fallback_segmentor
  translators:
    - punct_translator
    - table_translator
    - script_translator@pinyin
  filters:
    - simplifier
    - reverse_lookup_filter@pinyin_lookup

speller:
  alphabet: zyxwvutsrqponmlkjihgfedcba
  delimiter: " '"

translator:
  dictionary: wubi86

pinyin:
  tag: pinyin
  prefix: "`"
  dictionary: luna_pinyin
  tips: 【拼音】

pinyin_lookup:
  tags: [ pinyin ]
  dictionary: wubi86
  overwrite_comment: true

punctuator:
  import_preset: symbols

key_binder:
  import_preset: default

recognizer:
  import_preset: default
  patterns:
    pinyin: "`[a-z]*;?$"
    punct: "^/[0-9]?[a-z]*$"
```
